---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package and php support for apache and update
    apt: 
       name: 
          - apache2
          - libapache2-mod-php 
          - unzip 
       state: latest
       update_cache: yes
    when: ansible_distribution == "Ubuntu"
   

  - name: install httpd package and php package 
    yum:
       name: 
          - httpd
          - php
       state: latest
    when: ansible_distribution == "CentOS"

  - name: Copy defautl file for site
    tags: apache,apache2,httpd
    copy:
      src: defualt_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 
 
  - name: start the service (CentOS)
    tags: httpd,apache,apache2
    service:
       name: httpd
       state: started
       enabled: yes
    when: ansible_distribution == "CentOS"
   
  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd
    
 - name: restart the httpd service
   tags: apache,centos,httpd
   service:
       name: httpd
       state: restarted
   when: httpd.changed


- hosts: db_server
  become: true
  tasks:
  
  - name: Intall mariadb Package (CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: Install maridab Package (Ubuntu)
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks: 
     
    - name: Intall samba file server in Centos in Ubuntu
      package:
         name: samba
         state: latest

- hosts: workstation
  become: true
  tasks:
      
     - name: Intall terraform 
       unarchive:
          src: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
          dest: /usr/local/bin/
          remote_src: yes
          mode: 0755
          owner: root
          group: root

