---
- name: ntp tasks
  hosts: users
  tasks:
  - name: install nfs utils
    ansible.builtin.yum:
       name: nfs.utils
       state: present
 
  

  - name: Enable and run ntpd
    ansible.builtin.service:
       name: ntpd
       state: started
       enabled: true
