---
- name: Update web servers
  hosts: users

  tasks:
  - name: create directory /tmp/jet
    file:
        path: /tmp/jet
        state: directory
  - name: copy from /etc/fstab into /tmp/jet
    copy:
        src: /etc/fstab
        dest: /tmp/jet
        mode: 0755
