---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package and php support for apache and update
    apt: 
       name: 
          - apache2
          - libapache2-mod-php 
       state: latest
       update_cache: yes
    when: ansible_distribution == "Ubuntu"
   

  - name: install httpd package and php package 
    yum:
       name: 
          - httpd
          - php
       state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:
  
  - name: Intall mariadb Package (CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: Install maridab Package (Ubuntu)
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks: 
     
    - name: Intall samba file server in Centos in Ubuntu
      package:
         name: samba
         state: latest

