- name: Install local .exe files on Windows host
  hosts: windows
  gather_facts: no

  vars:
    installers:
      - name: "Chrome"
        path: "C:\\Users\\vehant\\Downloads\\ChromeSetup.exe"
        args: "/silent /install"
      - name: "7-Zip"
        path: "C:\\Users\\vehant\\Downloads\\7z2301-x64.exe"
        args: "/S"
      - name: "VLC"
        path: "C:\\Users\\vehant\\Downloads\\vlc-3.0.20-win64.exe"
        args: "/L=1033 /S"
      - name: "Adobe"
        path: "C:\\Users\\vehant\\Downloads\\AdbeRdr1012_en_US.exe"
        args: "/S"
      - name: "AnyDesk"
        path: "C:\\Users\\vehant\\Downloads\\AnyDesk.exe"
        args: "/S"
      - name: "FoxitReader"
        path: "C:\\Users\\vehant\\Downloads\\FoxitReader331_enu_Setup.exe"  # Fixed typo "paht"
        args: "/S"
      - name: "FreeFilesync"
        path: "C:\\Users\\vehant\\Downloads\\FreeFileSync_5.10_setup.exe"
        args: "/S"
      - name: "Libre Office"
        path: "C:\\Users\\vehant\\Downloads\\LibreOffice_5.1.3_Win_x86.msi"
        args: "/quiet"
      - name: "MasterPDF"
        path: "C:\\Users\\vehant\\Downloads\\MasterPDFEditor-setup-x64.msi"
        args: "/quiet"
      - name: "Teams"
        path: "C:\\Users\\vehant\\Downloads\\MSTeamsSetup.exe"
        args: "/S"
      - name: "OpenVPN"
        path: "C:\\Users\\vehant\\Downloads\\openvpn-install-2.4.8-I602-Win10.exe"
        args: "/S"
      - name: "Skype"
        path: "C:\\Users\\vehant\\Downloads\\Skype-8.68.0.96.exe"
        args: "/S"
      - name: "TeamViewer"
        path: "C:\\Users\\vehant\\Downloads\\TeamViewer_Setup_en-ioc.exe"
        args: "/S"
      - name: "Thunderbird"
        path: "C:\\Users\\vehant\\Downloads\\thunderbird-102-1-1.exe"
        args: "/S"
      - name: "VLC (Old)"
        path: "C:\\Users\\vehant\\Downloads\\vlc-2.1.5-win64.exe"
        args: "/S"
      - name: "WinRAR"
        path: "C:\\Users\\vehant\\Downloads\\winrar-x64-550.exe"
        args: "/S"
      - name: "WinSCP"
        path: "C:\\Users\\vehant\\Downloads\\winscp517setup.exe"
        args: "/S"

  tasks:
    - name: Install software from local exe
      ansible.windows.win_shell: |
        Start-Process -FilePath "{{ item.path }}" -ArgumentList "{{ item.args }}" -Wait -NoNewWindow
      loop: "{{ installers }}"
      register: install_results

    - name: Show install results
      debug:
        var: install_results

