[windows]
10.33.11.88

[windows:vars]
ansible_user=desktop-5pruend\\vehant
ansible_password=VkWkp#20
ansible_connection=ssh
ansible_port=22
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_shell_type=powershell
ansible_become_method=runas
ansible_become_user=desktop-5pruend\\vehant

