- name: Install software on Windows machines
  hosts: windows
  gather_facts: no

  tasks:
    - name: Copy PowerShell install script to remote host
      ansible.windows.win_copy:
        src: /home/sarvind/ansible/install_local_apps.ps1
        dest: C:\Users\vehant\Documents\install_local_apps.ps1

    - name: Run the local install script
      ansible.windows.win_shell: |
         powershell -ExecutionPolicy Bypass -File C:\Users\vehant\Documents\install_local_apps.ps1


